### ISSUE TITLE
wdltool.jar - renamed to womtool.jar ? update docs

### ISSUE THREAD

**Issue by jayoung** [openwdl/wdl-docs#7]
hi there,

I'm new to WDL, enjoying the readthedocs site thanks to a recommendation from @vortexing

I got all excited when I read about `wdltool.jar` [here](https://wdl-docs.readthedocs.io/en/stable/WDL/specify_inputs/).  Took me a while to figure out why I couldn't find it in our local cromwell installation - looks like it's been renamed to `womtool.jar`?  

Would be great to update https://wdl-docs.readthedocs.io/en/stable/WDL/specify_inputs/ accordingly.

thanks!

Janet 

------------------------------------------------------------------- 
Dr. Janet Young 
Malik lab http://research.fhcrc.org/malik/en.html
Division of Basic Sciences
Fred Hutchinson Cancer Center
Seattle, WA, USA.
-------------------------------------------------------------------

**Comment by ekiernan** [comment]
Thank you so much, @jayoung! We put in a PR to fix the name and link to WOMtool: https://github.com/openwdl/wdl-docs/pull/8

**Comment by jayoung** [comment]
nice - thank you!

**Comment by ekiernan** [comment]
This PR is merged, so closing the issue for now.
